# Generated by Django 6.0.1 on 2026-01-27 08:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DataUpload",
            fields=[
                (
                    "upload_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "upload_timestamp",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("filename", models.CharField(max_length=255)),
                (
                    "record_count_transactions",
                    models.IntegerField(blank=True, null=True),
                ),
                ("record_count_customers", models.IntegerField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(default="active", max_length=50)),
            ],
            options={
                "db_table": "data_uploads",
            },
        ),
        migrations.CreateModel(
            name="ScenarioConfig",
            fields=[
                (
                    "scenario_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("scenario_name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("priority", models.CharField(blank=True, max_length=50, null=True)),
                ("frequency", models.CharField(blank=True, max_length=50, null=True)),
                ("transaction_types", models.JSONField(blank=True, null=True)),
                ("channels", models.JSONField(blank=True, null=True)),
                ("direction", models.CharField(blank=True, max_length=50, null=True)),
                ("thresholds", models.JSONField(blank=True, null=True)),
                ("lookback_days", models.IntegerField(blank=True, null=True)),
                (
                    "aggregation_logic",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("refinements", models.JSONField(blank=True, null=True)),
                ("config_json", models.JSONField(blank=True, null=True)),
                ("field_mappings", models.JSONField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "scenarios_config",
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("full_name", models.CharField(blank=True, max_length=255, null=True)),
                ("avatar_url", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "organization_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("role", models.CharField(default="analyst", max_length=50)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "profiles",
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "customer_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("raw_data", models.JSONField(default=dict)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "upload",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customers",
                        to="simulation.dataupload",
                    ),
                ),
            ],
            options={
                "db_table": "customers",
            },
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "account_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                (
                    "account_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "account_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("account_status", models.CharField(default="Active", max_length=50)),
                ("currency_code", models.CharField(default="GBP", max_length=10)),
                ("account_open_date", models.DateTimeField()),
                ("account_close_date", models.DateTimeField(blank=True, null=True)),
                ("last_transaction_date", models.DateTimeField(blank=True, null=True)),
                ("risk_rating", models.TextField(blank=True, null=True)),
                ("is_pep", models.BooleanField(default=False)),
                (
                    "current_balance",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                (
                    "average_monthly_balance",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("raw_data", models.JSONField(default=dict)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounts",
                        to="simulation.customer",
                    ),
                ),
                (
                    "upload",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="simulation.dataupload",
                    ),
                ),
            ],
            options={
                "db_table": "accounts",
            },
        ),
        migrations.CreateModel(
            name="SimulationRun",
            fields=[
                (
                    "run_id",
                    models.CharField(
                        default=uuid.uuid4,
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("run_type", models.CharField(blank=True, max_length=50, null=True)),
                ("scenarios_run", models.JSONField(blank=True, null=True)),
                ("date_range_start", models.DateTimeField(blank=True, null=True)),
                ("date_range_end", models.DateTimeField(blank=True, null=True)),
                ("total_transactions", models.IntegerField(default=0)),
                ("total_alerts", models.IntegerField(blank=True, null=True)),
                ("status", models.CharField(blank=True, max_length=50, null=True)),
                ("progress_percentage", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("metadata_info", models.JSONField(blank=True, null=True)),
                (
                    "upload",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="simulation_runs",
                        to="simulation.dataupload",
                    ),
                ),
            ],
            options={
                "db_table": "simulation_runs",
            },
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "alert_id",
                    models.CharField(
                        default=uuid.uuid4,
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "scenario_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("scenario_description", models.TextField(blank=True, null=True)),
                ("alert_date", models.DateTimeField()),
                ("alert_status", models.CharField(default="OPN", max_length=50)),
                ("trigger_details", models.JSONField(blank=True, null=True)),
                (
                    "risk_classification",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("risk_score", models.IntegerField(blank=True, null=True)),
                ("excluded", models.BooleanField(default=False)),
                ("exclusion_reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "investigation_status",
                    models.CharField(default="New", max_length=50),
                ),
                ("outcome", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "sar_reference",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("investigation_notes", models.TextField(blank=True, null=True)),
                ("is_anonymized", models.BooleanField(default=False)),
                ("anonymized_at", models.DateTimeField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alerts",
                        to="simulation.customer",
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alerts",
                        to="simulation.scenarioconfig",
                    ),
                ),
                (
                    "simulation_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="simulation.simulationrun",
                    ),
                ),
            ],
            options={
                "db_table": "alerts",
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "transaction_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("raw_data", models.JSONField(default=dict)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="simulation.customer",
                    ),
                ),
                (
                    "upload",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="simulation.dataupload",
                    ),
                ),
            ],
            options={
                "db_table": "transactions",
            },
        ),
        migrations.CreateModel(
            name="AlertTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contribution_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("is_primary_trigger", models.BooleanField(default=False)),
                ("sequence_order", models.IntegerField(blank=True, null=True)),
                (
                    "alert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_transactions",
                        to="simulation.alert",
                    ),
                ),
                (
                    "upload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="simulation.dataupload",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_transactions",
                        to="simulation.transaction",
                    ),
                ),
            ],
            options={
                "db_table": "alert_transactions",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("alert", "transaction"), name="unique_alert_transaction"
                    )
                ],
            },
        ),
    ]
