# Generated by Django 6.0.1 on 2026-01-27 09:24

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulation", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "log_id",
                    models.CharField(
                        default=uuid.uuid4,
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("user_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "action_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "target_entity_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("details", models.JSONField(blank=True, null=True)),
                ("risk_score_snapshot", models.FloatField(blank=True, null=True)),
                ("justification_notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "audit_logs",
            },
        ),
        migrations.CreateModel(
            name="VerifiedEntity",
            fields=[
                (
                    "entity_id",
                    models.CharField(
                        default=uuid.uuid4,
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "entity_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "entity_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "risk_category",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("valid_from", models.DateTimeField(default=django.utils.timezone.now)),
                ("valid_to", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "verified_entities",
            },
        ),
        migrations.AddField(
            model_name="dataupload",
            name="schema_snapshot",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dataupload",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="uploads",
                to="simulation.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="scenarioconfig",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scenarios",
                to="simulation.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="simulationrun",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="simulation_runs",
                to="simulation.userprofile",
            ),
        ),
        migrations.CreateModel(
            name="AlertExclusionLog",
            fields=[
                (
                    "log_id",
                    models.CharField(
                        default=uuid.uuid4,
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "exclusion_timestamp",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("rule_id", models.CharField(blank=True, max_length=255, null=True)),
                ("exclusion_reason", models.TextField(blank=True, null=True)),
                ("risk_flags", models.JSONField(blank=True, null=True)),
                (
                    "alert",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exclusion_logs",
                        to="simulation.alert",
                    ),
                ),
            ],
            options={
                "db_table": "alert_exclusion_logs",
            },
        ),
        migrations.CreateModel(
            name="BeneficiaryHistory",
            fields=[
                (
                    "history_id",
                    models.CharField(
                        default=uuid.uuid4,
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "beneficiary_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "beneficiary_account",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("total_transactions", models.IntegerField(default=0)),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("first_seen", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_seen", models.DateTimeField(default=django.utils.timezone.now)),
                ("std_dev_amount", models.FloatField(blank=True, null=True)),
                ("avg_days_between_txns", models.FloatField(blank=True, null=True)),
                (
                    "upload",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="beneficiary_history",
                        to="simulation.dataupload",
                    ),
                ),
            ],
            options={
                "db_table": "beneficiary_history",
            },
        ),
        migrations.CreateModel(
            name="ComparisonReport",
            fields=[
                (
                    "report_id",
                    models.CharField(
                        default=uuid.uuid4,
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "report_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("report_data", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "run",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comparison_reports",
                        to="simulation.simulationrun",
                    ),
                ),
            ],
            options={
                "db_table": "comparison_reports",
            },
        ),
        migrations.CreateModel(
            name="CustomerRiskProfile",
            fields=[
                (
                    "profile_id",
                    models.CharField(
                        default=uuid.uuid4,
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_pep", models.BooleanField(default=False)),
                ("high_risk_occupation", models.BooleanField(default=False)),
                ("has_adverse_media", models.BooleanField(default=False)),
                ("previous_sar_count", models.IntegerField(default=0)),
                ("account_age_days", models.IntegerField(default=0)),
                (
                    "last_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_profiles",
                        to="simulation.customer",
                    ),
                ),
            ],
            options={
                "db_table": "customer_risk_profiles",
            },
        ),
        migrations.CreateModel(
            name="DataQualityMetrics",
            fields=[
                (
                    "metric_id",
                    models.CharField(
                        default=uuid.uuid4,
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("completeness_score", models.FloatField(blank=True, null=True)),
                ("validity_score", models.FloatField(blank=True, null=True)),
                ("uniqueness_score", models.FloatField(blank=True, null=True)),
                ("field_level_issues", models.JSONField(blank=True, null=True)),
                ("row_level_issues", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "upload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quality_metrics",
                        to="simulation.dataupload",
                    ),
                ),
            ],
            options={
                "db_table": "data_quality_metrics",
            },
        ),
        migrations.CreateModel(
            name="FieldMetadata",
            fields=[
                (
                    "metadata_id",
                    models.CharField(
                        default=uuid.uuid4,
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("table_name", models.CharField(max_length=100)),
                ("field_name", models.CharField(max_length=100)),
                ("field_type", models.CharField(max_length=50)),
                ("total_records", models.IntegerField(blank=True, null=True)),
                ("non_null_count", models.IntegerField(blank=True, null=True)),
                ("null_count", models.IntegerField(blank=True, null=True)),
                ("distinct_count", models.IntegerField(blank=True, null=True)),
                (
                    "min_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                (
                    "max_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                (
                    "avg_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                ("recommended_operators", models.JSONField(blank=True, null=True)),
                ("sample_values", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "upload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_metadata",
                        to="simulation.dataupload",
                    ),
                ),
            ],
            options={
                "db_table": "field_metadata",
            },
        ),
        migrations.CreateModel(
            name="FieldValueIndex",
            fields=[
                (
                    "index_id",
                    models.CharField(
                        default=uuid.uuid4,
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("table_name", models.CharField(max_length=100)),
                ("field_name", models.CharField(max_length=100)),
                ("field_value", models.CharField(max_length=500)),
                ("value_count", models.IntegerField(default=1)),
                (
                    "value_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("first_seen", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_seen", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "upload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_value_index",
                        to="simulation.dataupload",
                    ),
                ),
            ],
            options={
                "db_table": "field_value_index",
            },
        ),
        migrations.CreateModel(
            name="ScenarioVersion",
            fields=[
                (
                    "version_id",
                    models.CharField(
                        default=uuid.uuid4,
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version_number", models.IntegerField()),
                ("config_snapshot", models.JSONField(blank=True, null=True)),
                ("change_description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="simulation.userprofile",
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="simulation.scenarioconfig",
                    ),
                ),
            ],
            options={
                "db_table": "scenario_versions",
            },
        ),
        migrations.CreateModel(
            name="SimulationComparison",
            fields=[
                (
                    "comparison_id",
                    models.CharField(
                        default=uuid.uuid4,
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("alerts_delta", models.IntegerField(blank=True, null=True)),
                ("efficiency_score", models.FloatField(blank=True, null=True)),
                ("overlap_count", models.IntegerField(blank=True, null=True)),
                ("comparison_details", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "base_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="base_comparisons",
                        to="simulation.simulationrun",
                    ),
                ),
                (
                    "challenger_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="challenger_comparisons",
                        to="simulation.simulationrun",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="simulation.userprofile",
                    ),
                ),
            ],
            options={
                "db_table": "simulation_comparisons",
            },
        ),
    ]
