# Generated by Django 6.0.1 on 2026-01-28 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulation", "0003_dataupload_dataset_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="trigger_reason",
            field=models.TextField(blank=True, null=True),
        ),
    ]
